### PR TITLE
Fix Incubator breaking with item outputs

### PR DESCRIPTION
**Pull request by Lyfts**
Not entirely sure why this works, but I have tested it for a while and haven't ran into any problems.

Closes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13885

### CODE REVIEW

**Comment by minecraft7771** [comment]
Did you check if this causes bugs when putting circuits into electrical stimulator (with and without shift click)

**Comment by minecraft7771** [comment]
> Also just tested the version of binnie in current stable, and I am able to place a full stack of circuits with shift click. Seems like the previous patch didn't fix it with shift click either.

Was something in another mod changed? When I made my PR that added the lines you remove here, shift-clicking a full stack only took away 1.

**Comment by Lyfts** [comment]
It does only remove 1 if you only click 1 time... Shift clicking again adds the rest of the stack.

**Comment by Lyfts** [comment]
I have managed to fix the old patch's stacking problem, but I can't for the life of me get it to not void excess circuits on shift click whilst still keeping the incubator operational.

**Comment by minecraft7771** [comment]
> I have managed to fix the old patch's stacking problem, but I can't for the life of me get it to not void excess circuits on shift click whilst still keeping the incubator operational.

I think you need to fix the incubator on incubator side and not in the request. But just a guess.

**Comment by Lyfts** [comment]
I'm not too sure about that. From what I can tell it is sending the transfer requests correctly and it was working fine prior to the stimulator change. But for now I'll be closing this.

**Pull request closed without merging**
