### PR TITLE
No more restriction by player name

### PR DESCRIPTION
**Pull request by mitchej123**
The restriction on who can breed a bee has always annoyed me, it's more than cosmetic (like capes), and the ultimate goal seems to be to give acknowledgement to an individual or group of individuals, due to their contributions related to bees.

To that end, this removes the lock on names, and instead gives credits/acknowledgement to the people instead.

### CODE REVIEW

**Comment by Alastors** [comment]
It’s a bee that offers basically nothing except good genetics, it harms nothing it’s just a fun footnote

**Comment by Caedis** [comment]
Still doesnt need to be limited to a single person

**Review by Caedis — APPROVED** [review]

**Review by Connor-Colenso — APPROVED** [review]
I agree here, it should be a tribute to the user, not fully restrict anyone else ever getting it.

**Comment by Alastors** [comment]
It needs to be made clear exactly what bees this is effecting, some people are saying it’s just the new bee and others are saying it’s all UUID bees

**Comment by Caedis** [comment]
Its affecting all of them. None are limited to being breedable by a single person

**Comment by mitchej123** [comment]
> It needs to be made clear exactly what bees this is effecting, some people are saying it’s just the new bee and others are saying it’s all UUID bees

It's exactly 2 existing, 1 new.  Just search for usages of the function call `restrictPerson`.  Jaded, Chad, and whatever the new one is.

**Review by chochem — DISMISSED** [review]
chad should not be breedable at all then.

**Comment by mitchej123** [comment]
> chad should not be breedable at all then.

Why?  Is it OP?  If it's OP why was it ever allowed in for anyone?  If it's not, why not let everyone use it?

**Comment by chochem** [comment]
you get it for the gigachadtoken

**Comment by Alastors** [comment]
> > chad should not be breedable at all then.
> 
> 
> 
> Why?  Is it OP?  If it's OP why was it ever allowed in for anyone?  If it's not, why not let everyone use it?

Everyone already can use it, it's just a few people related to bee run got it directly while normal uses get a special method of getting it, it only has a slight bonus on a single genetic

**Review by Connor-Colenso — CHANGES_REQUESTED** [review]
I didn't realise this applied to more than just this bee tbh, I agree with the spirit of what Mitch has tried to do here but perhaps there is a compromise here. 

- Chad bee is quest obtainable anyway iirc, so not that big of a concern. But not 100% what it even does.
- The new bee, I think should be changed to as Mitch has done here. Tribute to the user, not restricted to them.
- Jaded I don't think anyone really cares, but maybe could use the same treatment as above.

**Review by Connor-Colenso — APPROVED** [review]

**Comment by Nilau1998** [comment]
Hey guys? Ok I get it, you hate that the change is permitted to just one person, but how about just saying that and leaving it open so I can repond to it?

Unknown info: Right after Dreams message, Diddy and I already gave more thought into it. As in, how can me make it more special, how can we make it more public. The birthday idea is an amazing point.

**Comment by Alastors** [comment]
> Hey guys? Ok I get it, you hate that the change is permitted to just one person, but how about just saying that and leaving it open so I can repond to it?
> 
> 
> 
> Unknown info: Right after Dreams message, Diddy and I already gave more thought into it. As in, how can me make it more special, how can we make it more public. The birthday idea is an amazing point.

Yeah honestly this was prolly merged a bit preemptively

**Comment by mitchej123** [comment]
> Hey guys? Ok I get it, you hate that the change is permitted to just one person, but how about just saying that and leaving it open so I can repond to it?

I've actually disliked it since I originally saw the Jaded bee.  I like the idea of credit/inspiration/acknowledgements, which is why the tooltips were left in.  Limiting to one person to breed, as a feature, is more than cosmetic and felt like it had little place in the pack.

With this change, you can leave it as is on the other PR, and add in the birthday week!

**Pull request merged**
